# Generated by Django 5.2.7 on 2026-10-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(
                default="aud",
                help_text="Three-letter currency code, e.g. aud.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Amount charged at checkout, in cents (e.g. 1499 = $14.99). Used when no Stripe price ID is set.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Optional. A Price ID from Stripe (price_...). If set, it overrides price_cents.",
                max_length=255,
            ),
        ),
    ]
