# Generated by Django 5.2 on 2026-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqtest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Countdown length for this test. Leave blank for an untimed test.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="time_taken_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
