# Generated by Django 5.2 on 2026-10-09 09:30

import django.db.models.deletion
import iqtest.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqtest", "0002_category_time_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="currency",
            field=models.CharField(
                default="aud",
                help_text="Three-letter currency code, e.g. aud.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="price_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="One-off price in cents for a single attempt (e.g. 1000 = $10). When set, anyone -- logged in or not -- must buy a test pass to take this test. Leave blank for the normal free/Premium rules.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TestPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=iqtest.models._new_pass_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Taken from Stripe Checkout once paid.",
                        max_length=254,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_pass",
                        to="iqtest.testattempt",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passes",
                        to="iqtest.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set if the buyer happened to be logged in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
